console.log("vocab.js loaded");

// Full Latin vocabulary embedded directly into the JavaScript code
const vocabulary = [
    { "Headword": "ā ab abs", "Definition": "from, by (+abl.)" },
    { "Headword": "abeō -īre -iī -itum", "Definition": "go away" },
    { "Headword": "absum abesse āfuī", "Definition": "be away, absent" },
    { "Headword": "ac", "Definition": "and in addition, and also, and; (after comparatives) than; simul ac, as soon as; → atque" },
    { "Headword": "accēdō -cēdere -cessī -cessum", "Definition": "approach" },
    { "Headword": "accidō -cidere -cidī", "Definition": "fall; happen" },
    { "Headword": "accipiō -cipere -cēpī -ceptum", "Definition": "receive" },
    { "Headword": "ācer ācris ācre", "Definition": "sharp, piercing" },
    { "Headword": "aciēs -ēī f.", "Definition": "edge; line of battle" },
    { "Headword": "ad", "Definition": "to, up to, towards (+acc.)" },
    { "Headword": "addō -dere -didī -ditum", "Definition": "give to" },
    { "Headword": "addūcō -ere -dūxī -ductum", "Definition": "lead to, induce" },
    { "Headword": "adeō -īre -iī -itum", "Definition": "go to" },
    { "Headword": "adeō", "Definition": "(adv.) to such a degree, so" },
    { "Headword": "adhibeō -hibēre -hibuī -hibitum", "Definition": "apply" },
    { "Headword": "adhūc", "Definition": "thus far, to this point" },
    { "Headword": "adveniō -īre -vēnī -ventum", "Definition": "come to, arrive at" },
    { "Headword": "adversus -a -um", "Definition": "facing, opposed; unfavorable" },
    { "Headword": "adversus (-um)", "Definition": "(adv. and prep.) facing, opposite, against, opposed (to)" },
    { "Headword": "advertō -vertere -vertī -versum", "Definition": "turn towards" },
    { "Headword": "aedēs -is f.", "Definition": "building; (pl.) house" },
    { "Headword": "aeger aegra aegrum", "Definition": "sick" },
    { "Headword": "aegrē", "Definition": "with difficulty" },
    { "Headword": "aequē", "Definition": "equally" },
    { "Headword": "aequor aequoris n.", "Definition": "level surface, sea, plain" },
    { "Headword": "aequus -a -um", "Definition": "equal" },
    { "Headword": "āēr āeris m.", "Definition": "air" },
    { "Headword": "aes aeris n.", "Definition": "copper, bronze" },
    { "Headword": "aetās -tātis f.", "Definition": "age, time of life" },
    { "Headword": "aeternus -a -um", "Definition": "everlasting, eternal" },
    { "Headword": "aethēr aetheris n.", "Definition": "pure upper air, ether, heaven, sky" },
    { "Headword": "aevum -i n.", "Definition": "eternity; lifetime, age" },
    { "Headword": "afferō afferre attulī allātum", "Definition": "bring to" },
    { "Headword": "afficiō -ficere -fēcī -fectum", "Definition": "affect, visit with (+ abl.)" },
    { "Headword": "ager agrī m.", "Definition": "field" },
    { "Headword": "agitō -āre", "Definition": "drive" },
    { "Headword": "āgmen -minis n.", "Definition": "line of march" },
    { "Headword": "agō agere ēgī āctum", "Definition": "drive, do, act" },
    { "Headword": "aiō", "Definition": "say, affirm, say yes; ut āiunt: as they say" },
    { "Headword": "albus -a -um", "Definition": "white" },
    { "Headword": "aliēnus -a -um", "Definition": "foreign, strange" },
    { "Headword": "aliquandō", "Definition": "at some time, at length" },
    { "Headword": "aliquis -quae -quod", "Definition": "some, any; si quis, si quid: anyone who, anything that" },
    { "Headword": "aliter", "Definition": "otherwise, differently" },
    { "Headword": "alius -a -ud", "Definition": "other, another; ālias: at another time" },
    { "Headword": "alō alere aluī alitum", "Definition": "nourish" },
    { "Headword": "alter altera alterum", "Definition": "other of two" },
    { "Headword": "altus -a -um", "Definition": "high, lofty; deep" },
    { "Headword": "amīcitia -ae f.", "Definition": "friendship" },
    { "Headword": "amīcus -a -um", "Definition": "friendly; (as subst.) friend" },
    { "Headword": "āmittō -mittere -mīsī -missum", "Definition": "let go, send away" },
    { "Headword": "amnis -is m.", "Definition": "river, torrent" },
    { "Headword": "amō -āre", "Definition": "to love; amāns -ntis m./f.: lover" },
    { "Headword": "amor -ōris m.", "Definition": "love" },
    { "Headword": "amplus -a -um", "Definition": "large, spacious" },
    { "Headword": "an", "Definition": "or (in questions); utrum ... an: whether ... or" },
    { "Headword": "anima -ae f.", "Definition": "breath, spirit" },
    { "Headword": "animal -ālis n.", "Definition": "a living being, an animal" },
    { "Headword": "animus -ī m.", "Definition": "spirit, mind" },
    { "Headword": "annus -ī m.", "Definition": "year" },
    { "Headword": "ante", "Definition": "before, in front of (adv. and prep. + acc.)" },
    { "Headword": "antequam", "Definition": "before" },
    { "Headword": "antīquus -a -um", "Definition": "ancient, old-time, former" },
    { "Headword": "aperiō aperīre aperuī apertum", "Definition": "open" },
    { "Headword": "appāreō -ēre -uī", "Definition": "appear, become visible" },
    { "Headword": "appellō -pellāre", "Definition": "call, address, name" },
    { "Headword": "aptus -a -um", "Definition": "fit, suitable" },
    { "Headword": "apud", "Definition": "near, in the presence of (+acc.)" },
    { "Headword": "aqua -ae f.", "Definition": "water" },
    { "Headword": "āra -ae f.", "Definition": "altar" },
    { "Headword": "arbitror arbitrārī arbitrātus sum", "Definition": "consider, think" },
    { "Headword": "arbor arboris f.", "Definition": "tree" },
    { "Headword": "ārdeō ārdēre ārsī ārsum", "Definition": "blaze, glow; be eager" },
    { "Headword": "argentum -ī n.", "Definition": "silver, money" },
    { "Headword": "arma -ōrum n. pl.", "Definition": "arms, weapons" },
    { "Headword": "ars artis f.", "Definition": "skill" },
    { "Headword": "arvum -ī n.", "Definition": "ploughed land, field" },
    { "Headword": "arx arcis f.", "Definition": "citadel, castle; summit" },
    { "Headword": "ascendō -ere -scendī -scēnsum", "Definition": "climb up, ascend" },
    { "Headword": "aspiciō -ere -spēxī -spectum", "Definition": "look to or at, behold" },
    { "Headword": "adsum adesse affuī", "Definition": "be present" },
    { "Headword": "astrum -ī n.", "Definition": "star; constellation" },
    { "Headword": "at", "Definition": "but, but yet" },
    { "Headword": "atque", "Definition": "and in addition, and also, and; (after comparatives) than; simul atque, as soon as; → ac" },
    { "Headword": "auctor -ōris m.", "Definition": "originator, founder" },
    { "Headword": "auctōritās -ātis f.", "Definition": "influence, clout, authority" },
    { "Headword": "audāx audācis", "Definition": "bold, daring; reckless" },
    { "Headword": "audeō audēre ausus sum", "Definition": "dare, be eager" },
    { "Headword": "audiō -īre -īvī/-iī -ītum", "Definition": "hear, listen to" },
    { "Headword": "auferō auferre abstulī ablātum", "Definition": "take away" },
    { "Headword": "augeō augēre auxī auctum", "Definition": "increase" },
    { "Headword": "avis -is f.", "Definition": "bird" },
    { "Headword": "aura -ae f.", "Definition": "breeze" },
    { "Headword": "aureus -a -um", "Definition": "golden; splendid" },
    { "Headword": "auris -is f.", "Definition": "ear" },
    { "Headword": "aurum -ī n.", "Definition": "gold" },
    { "Headword": "aut", "Definition": "or" },
    { "Headword": "autem", "Definition": "moreover, but, however" },
    { "Headword": "auxilium -ī n.", "Definition": "support, assistance; (pl.) auxiliary forces" },
    { "Headword": "barbarus -ī m.", "Definition": "foreigner, barbarian" },
    { "Headword": "beātus -a -um", "Definition": "happy, blessed, prosperous, fortunate" },
    { "Headword": "bellum -ī n.", "Definition": "war" },
    { "Headword": "bene", "Definition": "well" },
    { "Headword": "beneficium -ī n.", "Definition": "service, kindness" },
    { "Headword": "bonus -a -um", "Definition": "good" },
    { "Headword": "bōs bovis m.", "Definition": "ox; gen. pl. boum" },
    { "Headword": "brevis -e", "Definition": "short, shallow, brief" },
    { "Headword": "breviter", "Definition": "briefly" },
    { "Headword": "cadō cadere cecidī cāsum", "Definition": "fall, be killed" },
    { "Headword": "caecus -a -um", "Definition": "blind, unseeing; dark, obscure" },
    { "Headword": "caedēs -is f.", "Definition": "killing, slaughter" },
    { "Headword": "caedō caedere cecīdī caesum", "Definition": "strike, kill, cut down" },
    { "Headword": "caelestis -e", "Definition": "from or of heaven; caelestēs, the gods" },
    { "Headword": "caelum -ī n.", "Definition": "sky, heavens" },
    { "Headword": "campus -ī m.", "Definition": "plain, field" },
    { "Headword": "candidus -a -um", "Definition": "white, fair" },
    { "Headword": "canis -is m./f.", "Definition": "dog" },
    { "Headword": "canō canere cecinī cantum", "Definition": "sing" },
    { "Headword": "capiō capere cēpī captum", "Definition": "seize" },
    { "Headword": "caput capitis n.", "Definition": "head" },
    { "Headword": "careō -ēre -uī", "Definition": "lack (+ abl.)" },
    { "Headword": "carmen -inis n.", "Definition": "song" },
    { "Headword": "cārus -a -um", "Definition": "dear" },
    { "Headword": "castrum -ī n.", "Definition": "fortress, (regularly plural, castra camp)" },
    { "Headword": "castus -a -um", "Definition": "pure, spotless, chaste" },
    { "Headword": "cāsus -ūs m.", "Definition": "a fall; chance, accident" },
    { "Headword": "caveō cavēre cāvī cautum", "Definition": "be on guard, beware" },
    { "Headword": "causa -ae f.", "Definition": "cause, reason; causā + preceding genitive, for the sake of" },
    { "Headword": "cēdō cēdere cessī cessum", "Definition": "go, move; yield" },
    { "Headword": "celebrō -āre", "Definition": "frequent, throng, crowd" },
    { "Headword": "celer -is -e", "Definition": "swift" },
    { "Headword": "celeriter", "Definition": "quickly" },
    { "Headword": "cēnseō cēnsēre cēnsuī cēnsum", "Definition": "assess, rate; think, decide" },
    { "Headword": "centum", "Definition": "one hundred" },
    { "Headword": "cernō cernere crēvī crētum", "Definition": "discern, separate" },
    { "Headword": "certē", "Definition": "certainly, surely" },
    { "Headword": "certō -āre", "Definition": "decide by contest; fight, compete, vie" },
    { "Headword": "certus -a -um", "Definition": "sure, fixed" },
    { "Headword": "cēterum", "Definition": "for the rest, in addition, however that may be" },
    { "Headword": "cēterus -a -um", "Definition": "the other, the others, the rest" },
    { "Headword": "cibus -ī m.", "Definition": "food" },
    { "Headword": "cingō cingere cīnxī cīnctum", "Definition": "encircle, surround, gird" },
    { "Headword": "cinis cineris m./f.", "Definition": "ashes, embers" },
    { "Headword": "circā", "Definition": "around (adv. and prep. +acc.)" },
    { "Headword": "citus -a -um", "Definition": "swift; citō swiftly" },
    { "Headword": "cīvis -is m./f.", "Definition": "citizen" },
    { "Headword": "cīvitās -ātis f.", "Definition": "citizenship, state" },
    { "Headword": "clāmor -ōris m.", "Definition": "outcry, shout" },
    { "Headword": "clārus -a -um", "Definition": "clear, distinguished" },
    { "Headword": "classis -is f.", "Definition": "class, division, fleet" },
    { "Headword": "claudō claudere clausī clausum", "Definition": "close, shut" },
    { "Headword": "coepī coepisse coeptus", "Definition": "begin" },
    { "Headword": "cōgitō -āre", "Definition": "think, reflect" },
    { "Headword": "cōgnōscō -gnōscere -gnōvī -gnitum", "Definition": "learn, understand" },
    { "Headword": "cōgō cōgere coēgī coāctum", "Definition": "drive together; compel" },
    { "Headword": "cohors cohortis f.", "Definition": "cohort, band, troop" },
    { "Headword": "colligō -ere -lēgī -lēctum", "Definition": "gather together, collect" },
    { "Headword": "colō colere coluī cultum", "Definition": "inhabit, cultivate" },
    { "Headword": "color -ōris m.", "Definition": "color" },
    { "Headword": "coma -ae f.", "Definition": "hair, tresses" },
    { "Headword": "comes comitis m./f.", "Definition": "companion, comrade; attendant, follower" },
    { "Headword": "committō -mittere -mīsī -missum", "Definition": "join, entrust to (+ dat.); perform, do" },
    { "Headword": "commūnis -e", "Definition": "common, general" },
    { "Headword": "comparō -āre", "Definition": "get ready, provide; compare" },
    { "Headword": "compōnō -pōnere posuī positum", "Definition": "build, construct, arrange" },
    { "Headword": "concēdō -cēdere -cessī -cessum", "Definition": "yield, withdraw" },
    { "Headword": "condīciō -ōnis f.", "Definition": "agreement, condition" },
    { "Headword": "condō -dere -didī -ditum", "Definition": "build, found; store up; hide, conceal" },
    { "Headword": "cōnferō cōnferre contulī collātum", "Definition": "collect, bring to" },
    { "Headword": "cōnficiō -ficere -fēcī -fectum", "Definition": "complete, accomplish; destroy, kill, consume" },
    { "Headword": "cōnfiteor cōnfitērī cōnfessus sum", "Definition": "admit (a fact), confess (a crime); reveal, disclose" },
    { "Headword": "coniunx coniugis m./f.", "Definition": "spouse, husband, wife" },
    { "Headword": "cōnor cōnārī cōnātus sum", "Definition": "try, attempt" },
    { "Headword": "cōnsequor -sequī -secūtus sum", "Definition": "follow up, overtake, attain" },
    { "Headword": "cōnsilium -ī n.", "Definition": "plan; council, group of advisors" },
    { "Headword": "cōnsistō -sistere -stitī", "Definition": "take position; consist in, be composed of" },
    { "Headword": "cōnstituō -stituere -stituī -stitūtum", "Definition": "establish, put together" },
    { "Headword": "cōnstō -stāre -stitī", "Definition": "agree; constat, it is established that (+ acc. and infin.)" },
    { "Headword": "cōnsuētūdo -inis f.", "Definition": "custom, habit" },
    { "Headword": "cōnsul -ulis m.", "Definition": "consul" },
    { "Headword": "cōnsulō -sulere -suluī -sultum", "Definition": "consult, plan (+ acc.); consider the interests of (+dat)" },
    { "Headword": "cōnsūmō -sūmere -sūmpsī -sūmptum", "Definition": "to use up, consume" },
    { "Headword": "contemnō -temnere -tempsī -temptum", "Definition": "despise, scorn, disdain" },
    { "Headword": "contineō -tinēre -tinuī -tentum", "Definition": "contain, restrain" },
    { "Headword": "contingō -tingere -tigī -tactum", "Definition": "touch, be contiguous to" },
    { "Headword": "contrā", "Definition": "against, opposite (adv. and prep. +acc.)" },
    { "Headword": "conveniō -venīre -vēnī -ventum", "Definition": "assemble, meet; agree" },
    { "Headword": "convertō -vertere -vertī -versum", "Definition": "turn about, turn, change" },
    { "Headword": "convīvium -iī n.", "Definition": "banquet, feast" },
    { "Headword": "cōpia -ae f.", "Definition": "abundance; (pl.) troops" },
    { "Headword": "cor cordis n.", "Definition": "heart; cordī est, it is pleasing to (+ dat.)" },
    { "Headword": "cornu -ūs n.", "Definition": "horn" },
    { "Headword": "corpus corporis n.", "Definition": "body" },
    { "Headword": "corrumpō -rumpere -rūpī -ruptum", "Definition": "break up, destroy, ruin" },
    { "Headword": "crēdō crēdere crēdidī crēditum", "Definition": "believe" },
    { "Headword": "creō -āre", "Definition": "produce, create; elect, choose" },
    { "Headword": "crēscō crēscere crēvī crētum", "Definition": "grow, increase" },
    { "Headword": "crīmen -inis n.", "Definition": "verdict, accusation" },
    { "Headword": "culpa -ae f.", "Definition": "guilt, fault, blame" },
    { "Headword": "cum", "Definition": "with (prep. + abl.); when, since, although (conjunction + subj.)" },
    { "Headword": "cūnctus -a -um", "Definition": "entire all together" },
    { "Headword": "cupīdō -inis f.", "Definition": "desire, eagerness, craving" },
    { "Headword": "cupiō -ere -īvī -ītum", "Definition": "desire" },
    { "Headword": "cūr", "Definition": "why?" },
    { "Headword": "cūra -ae f.", "Definition": "care, concern" },
    { "Headword": "cūrō -āre", "Definition": "watch over, look after, care for (+ acc.)" },
    { "Headword": "currō currere cucurrī cursum", "Definition": "run" },
    { "Headword": "currus -ūs m.", "Definition": "chariot" },
    { "Headword": "cursus -ūs m.", "Definition": "course, advance" },
    { "Headword": "custōs custōdis m.", "Definition": "guardian" },
    { "Headword": "damnō -āre", "Definition": "condemn" },
    { "Headword": "damnum -ī n.", "Definition": "damage, injury" },
    { "Headword": "dē", "Definition": "down from, about, concerning (+ abl.)" },
    { "Headword": "dēbeō dēbēre dēbuī dēbitum", "Definition": "owe, be obliged" },
    { "Headword": "decem", "Definition": "ten" },
    { "Headword": "dēcernō -cernere -crēvī -crētum", "Definition": "determine, decide" },
    { "Headword": "decet decēre decuīt", "Definition": "it is right, proper, fitting (+ acc. + infin.)" },
    { "Headword": "decus decoris n.", "Definition": "beauty, grace; ornament, glory, honor" },
    { "Headword": "dēdūcō -dūcere -dūxī -ductum", "Definition": "launch, lead away" },
    { "Headword": "dēfendō -fendere -fendī -fēnsum", "Definition": "defend, ward off" },
    { "Headword": "dēferō -ferre -tulī -lātum", "Definition": "carry away, report" },
    { "Headword": "deficiō -ficere -fēcī -fectum", "Definition": "fail, give out; revolt from" },
    { "Headword": "deinde/dein", "Definition": "then, next" },
    { "Headword": "dēnique", "Definition": "finally" },
    { "Headword": "dēscendō -scendere -scendī -scēnsum", "Definition": "climb down, descend" },
    { "Headword": "dēserō -ere dēseruī dēsertum", "Definition": "leave, desert, abandon" },
    { "Headword": "dēsīderō -āre", "Definition": "long for, desire greatly" },
    { "Headword": "dēsinō -sinere -siī -situm", "Definition": "leave off, cease" },
    { "Headword": "dēsum -esse -fuī", "Definition": "be lacking" },
    { "Headword": "deus -ī m.; dea -ae f.", "Definition": "god; goddess" },
    { "Headword": "dexter -tra -trum", "Definition": "right; dextera -ae f.: right hand" },
    { "Headword": "dīcō dīcere dīxī dictum", "Definition": "say; causam dīcere, plead a case; diem dīcere, appoint a day" },
    { "Headword": "diēs diēī m./f.", "Definition": "day" },
    { "Headword": "differō differre distulī dīlātum", "Definition": "scatter; publish, divulge; differ; defer, postpone" },
    { "Headword": "difficilis -e", "Definition": "not easy, hard, difficult" },
    { "Headword": "dīgnitās -ātis f.", "Definition": "worth, reputation, honor" },
    { "Headword": "dīgnus -a -um", "Definition": "worthy" },
    { "Headword": "dīligō -ligere -lēxī -lēctum", "Definition": "choose, cherish, love" },
    { "Headword": "dīmittō -mittere -mīsī -missum", "Definition": "send away" },
    { "Headword": "discēdō -ere -cessī -cessum", "Definition": "go away, depart" },
    { "Headword": "disciplīna -ae f.", "Definition": "training, instruction; learning, discipline" },
    { "Headword": "discō -ere didicī", "Definition": "learn" },
    { "Headword": "diū:", "Definition": "for a long time" },
    { "Headword": "dīversus -a -um", "Definition": "different, diverse" },
    { "Headword": "dīves dīvitis", "Definition": "rich (poet. dīs, dītis)" },
    { "Headword": "dīvidō -ere dīvīsī dīvīsum", "Definition": "divide, separate" },
    { "Headword": "dīvitiae -ārum f. pl.", "Definition": "riches, wealth" },
    { "Headword": "dīvus -a -um", "Definition": "divine, godlike; (as subst.) a god" },
    { "Headword": "dō dare dedī datum", "Definition": "give" },
    { "Headword": "doceō -ēre -uī doctum", "Definition": "teach" },
    { "Headword": "doleō -ēre doluī", "Definition": "feel pain or grief, grieve" },
    { "Headword": "dolor -ōris m.", "Definition": "pain, grief" },
    { "Headword": "dolus -ī m.", "Definition": "artifice, device, trick" },
    { "Headword": "dominus -ī m.; domina -ae f.", "Definition": "household master, lord; mistress" },
    { "Headword": "domus -ūs f.", "Definition": "house, home" },
    { "Headword": "dōnec", "Definition": "until" },
    { "Headword": "dōnō -āre", "Definition": "present with a gift (+ acc. of person and abl. of thing)" },
    { "Headword": "dōnum -ī n.", "Definition": "gift, present" },
    { "Headword": "dormiō -īre", "Definition": "sleep" },
    { "Headword": "dubitō -āre", "Definition": "hesitate, doubt" },
    { "Headword": "dubius -a -um", "Definition": "doubtful; (as subst.) a doubt; sine dubiō, without a doubt, certainly" },
    { "Headword": "dūcō dūcere dūxī ductum", "Definition": "lead; uxōrem dūcere, marry" },
    { "Headword": "dulcis -e", "Definition": "sweet" },
    { "Headword": "dum", "Definition": "while (+ indic.); until (+ subj.); provided that (+ subj.)" },
    { "Headword": "duo duae duo", "Definition": "two" },
    { "Headword": "dūrus -a -um", "Definition": "hard, tough, harsh" },
    { "Headword": "dux ducis m./f.", "Definition": "leader, general" },
    { "Headword": "ecce", "Definition": "behold!" },
    { "Headword": "ēdīcō -dīcere -dīxī -dictum", "Definition": "declare" },
    { "Headword": "ēdō ēdere ēdidī ēditum", "Definition": "put forth, state, explain" },
    { "Headword": "ēdūcō -dūcere -dūxī -ductum", "Definition": "lead forth" },
    { "Headword": "efficiō -ficere -fēcī -fectum", "Definition": "bring about, complete; render (+ ut + subj.)" },
    { "Headword": "effundō -fundere -fūdī -fūsum", "Definition": "pour out" },
    { "Headword": "ego meī mihi mē", "Definition": "I, me" },
    { "Headword": "ēgredior ēgredī ēgressus sum", "Definition": "stride out, depart, disembark from (+ abl.)" },
    { "Headword": "ēgregius -a -um", "Definition": "distinguished, uncommon" },
    { "Headword": "ēligō ēligere ēlēgī ēlēctum", "Definition": "pick out, select" },
    { "Headword": "enim", "Definition": "for, indeed" },
    { "Headword": "eō īre iī/īvī itum", "Definition": "go" },
    { "Headword": "eō", "Definition": "(adv.) there, to that place" },
    { "Headword": "epistula -ae f.", "Definition": "letter" },
    { "Headword": "eques equitis m.", "Definition": "horseman, knight" },
    { "Headword": "equus -ī m.", "Definition": "horse" },
    { "Headword": "ergō", "Definition": "therefore" },
    { "Headword": "ēripiō -ripere -ripuī -reptum", "Definition": "snatch away, rescue, save" },
    { "Headword": "errō -āre", "Definition": "go astray, wander" },
    { "Headword": "error -ōris m.", "Definition": "wandering; error, mistake" },
    { "Headword": "et", "Definition": "and" },
    { "Headword": "etiam", "Definition": "also, even" },
    { "Headword": "ex, ē", "Definition": "out of, from (+ abl.)" },
    { "Headword": "excipiō -cipere -cēpī -ceptum", "Definition": "take out" },
    { "Headword": "exemplum -ī n.", "Definition": "example, sample, copy" },
    { "Headword": "exeō -īre -iī -itum", "Definition": "go forth" },
    { "Headword": "exerceō -ercēre -ercuī -ercitum", "Definition": "train, exercise, carry on" },
    { "Headword": "exercitus -ūs m.", "Definition": "army" },
    { "Headword": "exigō -igere -ēgī -āctum", "Definition": "drive out; collect" },
    { "Headword": "exīstimō -āre", "Definition": "think, believe" },
    { "Headword": "experior -perīrī -pertus sum", "Definition": "try thoroughly, test, experience" },
    { "Headword": "exsilium -ī n.", "Definition": "exile, banishment" },
    { "Headword": "exspectō -āre", "Definition": "watch, wait, expect" },
    { "Headword": "extrēmus -a -um", "Definition": "farthest, situated at the end or tip, extreme" },
    { "Headword": "fābula -ae f.", "Definition": "account, tale, story" },
    { "Headword": "faciēs -ēī f.", "Definition": "form, appearance" },
    { "Headword": "facilis -e", "Definition": "easy" },
    { "Headword": "facinus facinoris n.", "Definition": "deed, crime" },
    { "Headword": "faciō facere fēcī factum", "Definition": "do, make" },
    { "Headword": "factum -ī n.", "Definition": "deed, accomplishment" },
    { "Headword": "fallō fallere fefellī falsum", "Definition": "deceive" },
    { "Headword": "falsus -a -um", "Definition": "deceptive, false" },
    { "Headword": "fāma -ae f.", "Definition": "rumor, fame" },
    { "Headword": "famēs -is f.", "Definition": "hunger, famine" },
    { "Headword": "familia -ae f.", "Definition": "household, family" },
    { "Headword": "fateor fatērī fassus sum", "Definition": "admit, confess; profess, declare; assent, say yes" },
    { "Headword": "fātum -ī n.", "Definition": "fate; death" },
    { "Headword": "fax facis f.", "Definition": "torch" },
    { "Headword": "fēlīciter", "Definition": "luckily" },
    { "Headword": "fēlīx -īcis", "Definition": "lucky" },
    { "Headword": "fēmina -ae f.", "Definition": "woman" },
    { "Headword": "ferē", "Definition": "almost" },
    { "Headword": "ferō ferre tulī lātum", "Definition": "bear, carry, endure" },
    { "Headword": "ferrum -ī n.", "Definition": "iron, iron weapon or implement" },
    { "Headword": "ferus -a -um", "Definition": "wild, fierce; fera -ae f.: wild animal" },
    { "Headword": "fessus -a -um", "Definition": "weary, tired" },
    { "Headword": "fidēlis -e", "Definition": "faithful" },
    { "Headword": "fidēs -eī f.", "Definition": "trust, faith" },
    { "Headword": "fīlia -ae f.; fīlius -ī m.", "Definition": "daughter; son" },
    { "Headword": "fingō fingere fīnxī fīctum", "Definition": "shape; invent" },
    { "Headword": "fīnis -is m.", "Definition": "end, boundary" },
    { "Headword": "fīō fierī factus sum", "Definition": "become, happen, be done" },
    { "Headword": "flamma -ae f.", "Definition": "flame, fire" },
    { "Headword": "fleō flēre flēvī flētum", "Definition": "weep" },
    { "Headword": "flōs flōris m.", "Definition": "flower, bloom" },
    { "Headword": "fluctus -ūs m", "Definition": "flood, billow, surf" },
    { "Headword": "flūmen -inis n.", "Definition": "stream, river" },
    { "Headword": "fluō fluere fluxī fluxum", "Definition": "flow" },
    { "Headword": "foedus -a -um", "Definition": "foul" },
    { "Headword": "fōns fontis m.", "Definition": "spring, fountain" },
    { "Headword": "for fārī fātus sum", "Definition": "report, say" },
    { "Headword": "fōrma -ae f.", "Definition": "shape; beauty" },
    { "Headword": "fors fortis f.", "Definition": "chance" },
    { "Headword": "forsitan, fortasse", "Definition": "perhaps, perchance" },
    { "Headword": "forte", "Definition": "by chance" },
    { "Headword": "fortis -e", "Definition": "brave" },
    { "Headword": "fortūna -ae f.", "Definition": "fortune" },
    { "Headword": "forum -ī n.", "Definition": "market-place, forum" },
    { "Headword": "frangō frangere frēgī frāctum", "Definition": "break, shatter" },
    { "Headword": "frāter frātris m.", "Definition": "brother" },
    { "Headword": "frequēns -ntis", "Definition": "in large numbers, often" },
    { "Headword": "frōns frontis f.", "Definition": "forehead, brow; front" },
    { "Headword": "frūctus -ūs m.", "Definition": "fruit, crops; enjoyment, delight" },
    { "Headword": "frūmentum -ī n.", "Definition": "grain" },
    { "Headword": "fruor fruī frūctus sum", "Definition": "enjoy the produce of, profit by, use (+ abl.)" },
    { "Headword": "frūstrā", "Definition": "in vain" },
    { "Headword": "fuga -ae f.", "Definition": "flight, route" },
    { "Headword": "fugiō fugere fūgī fugitum", "Definition": "flee, escape" },
    { "Headword": "fugō -āre", "Definition": "put to flight" },
    { "Headword": "fundō fundere fūdī fūsum", "Definition": "pour, scatter" },
    { "Headword": "fūnus fūneris n.", "Definition": "funeral; death; dead body" },
    { "Headword": "furor -ōris m.", "Definition": "rage, fury" },
    { "Headword": "fore", "Definition": "null" },
    { "Headword": "gaudeō gaudēre gāvīsus sum", "Definition": "rejoice" },
    { "Headword": "gaudium -ī n.", "Definition": "delight, joy, pleasure" },
    { "Headword": "gēns gentis f.", "Definition": "family, clan" },
    { "Headword": "genus generis n.", "Definition": "origin, lineage, kind" },
    { "Headword": "gerō gerere gessī gestum", "Definition": "bear, manage; bellum gerere, wage war" },
    { "Headword": "gīgnō gīgnere genuī genitum", "Definition": "beget, bear, bring forth" },
    { "Headword": "gladius -ī m.", "Definition": "sword" },
    { "Headword": "glōria -ae f.", "Definition": "glory, fame" },
    { "Headword": "gradus -ūs m.", "Definition": "step, pace; grade, rank" },
    { "Headword": "grātia -ae f.", "Definition": "favor, influence, gratitude" },
    { "Headword": "grātus -a -um", "Definition": "pleasant; grateful" },
    { "Headword": "gravis -e", "Definition": "heavy, serious" },
    { "Headword": "habeō habēre habuī habitum", "Definition": "have, hold" },
    { "Headword": "haud", "Definition": "not" },
    { "Headword": "hic haec hoc", "Definition": "this, these" },
    { "Headword": "hīc", "Definition": "here; hinc: from here" },
    { "Headword": "hiems hiemis f.", "Definition": "winter" },
    { "Headword": "hodiē", "Definition": "today" },
    { "Headword": "homō hominis m.", "Definition": "human being" },
    { "Headword": "honestus -a -um", "Definition": "honorable" },
    { "Headword": "honor -ōris m.", "Definition": "honor, glory; office, post" },
    { "Headword": "hōra -ae f.", "Definition": "hour" },
    { "Headword": "hortor hortārī hortātus sum", "Definition": "urge strongly, advise, exhort" },
    { "Headword": "hospes hospitis m.", "Definition": "guest, guest-friend; stranger; host" },
    { "Headword": "hostis -is m./f.", "Definition": "stranger, enemy" },
    { "Headword": "hūc", "Definition": "to this place" },
    { "Headword": "hūmānus -a -um", "Definition": "human" },
    { "Headword": "humus -ī f.", "Definition": "ground; humī: on the ground" },
    { "Headword": "iaceō iacēre iacuī", "Definition": "lie" },
    { "Headword": "iaciō iacere iēcī iactum", "Definition": "throw, hurl" },
    { "Headword": "iam", "Definition": "now; already" },
    { "Headword": "ibi", "Definition": "there" },
    { "Headword": "īctus -ūs m.", "Definition": "blow, stroke" },
    { "Headword": "īdem eadem idem", "Definition": "the same" },
    { "Headword": "ideō", "Definition": "for this reason" },
    { "Headword": "igitur", "Definition": "therefore" },
    { "Headword": "ignis -is m.", "Definition": "fire" },
    { "Headword": "ille illa illud", "Definition": "that" },
    { "Headword": "illīc", "Definition": "at that place, there; illinc: from that place" },
    { "Headword": "illūc", "Definition": "to that place" },
    { "Headword": "imāgō -inis f.", "Definition": "image, form, figure" },
    { "Headword": "imperātor -ōris m.", "Definition": "commander" },
    { "Headword": "imperium -ī n.", "Definition": "command, power" },
    { "Headword": "imperō -āre", "Definition": "command, control" },
    { "Headword": "impetus -ūs m.", "Definition": "attack" },
    { "Headword": "impleō -ēre -plēvī -plētum", "Definition": "fill in, fill up" },
    { "Headword": "impōnō -ere -posuī -positum", "Definition": "put in, put on, impose, levy upon" },
    { "Headword": "in", "Definition": "in, on (+ abl.); into, onto (+ acc)" },
    { "Headword": "incidō incidere incidī", "Definition": "fall upon, fall into; happen" },
    { "Headword": "incipiō -cipere -cēpī -ceptum", "Definition": "begin" },
    { "Headword": "inde", "Definition": "from there, from then" },
    { "Headword": "indicō -āre", "Definition": "point out, show, make known" },
    { "Headword": "īnferō īnferre intulī illātum", "Definition": "bring upon, against; bellum īnferre: make war on" },
    { "Headword": "īnferus -a -um", "Definition": "low; īnferior: lower; īnfimus or īmus: lowest" },
    { "Headword": "ingenium -ī n.", "Definition": "disposition, ability, talent" },
    { "Headword": "ingēns ingentis", "Definition": "huge, enormous" },
    { "Headword": "ingrātus -a -um:", "Definition": "unpleasant, disagreeable" },
    { "Headword": "ingredior -gredī -gressus sum:", "Definition": "step in, enter" },
    { "Headword": "inimīcus -a -um:", "Definition": "unfriendly; (as subst.) enemy" },
    { "Headword": "initium -ī n.:", "Definition": "beginning" },
    { "Headword": "iniūria -ae f.:", "Definition": "injustice, wrong, affront" },
    { "Headword": "inquam, inquis, inquit, inquiunt:", "Definition": "say (used with direct speech)" },
    { "Headword": "īnstituō -stituere -stituī -stitūtum:", "Definition": "undertake; equip" },
    { "Headword": "īnsula -ae f.:", "Definition": "island" },
    { "Headword": "integer -gra -grum:", "Definition": "untouched, fresh, complete, whole" },
    { "Headword": "intellegō -legere -lēxī -lēctum:", "Definition": "understand" },
    { "Headword": "intendō -tendere -tendī -tentum:", "Definition": "stretch out, strain" },
    { "Headword": "inter", "Definition": "between, among; during (+ acc.)" },
    { "Headword": "interficiō -ficere -fēcī -fectum", "Definition": "kill" },
    { "Headword": "interim", "Definition": "meanwhile" },
    { "Headword": "interrogō -āre", "Definition": "put a question to, ask (+ acc.)" },
    { "Headword": "intersum -esse -fuī", "Definition": "to be between; take part in, attend (+dat.); interest, it is in the interest of (+ gen.)" },
    { "Headword": "intrā", "Definition": "within (+ acc.)" },
    { "Headword": "intrō -āre", "Definition": "enter" },
    { "Headword": "inveniō -venīre -vēnī -ventum", "Definition": "find; discover" },
    { "Headword": "invidia -ae f.", "Definition": "envy, jealousy, hatred" },
    { "Headword": "ipse ipsa ipsum", "Definition": "him- her- itself" },
    { "Headword": "īra irae f.", "Definition": "wrath, anger" },
    { "Headword": "īrāscor īrāscī īrātus sum", "Definition": "grow angry; īrātus -a -um: angry" },
    { "Headword": "is ea id", "Definition": "he, she, it" },
    { "Headword": "iste ista istud", "Definition": "that, that of yours; adv. istīc or istūc: over there; istinc: from over there" },
    { "Headword": "ita", "Definition": "thus, so" },
    { "Headword": "itaque", "Definition": "and so, therefore" },
    { "Headword": "item", "Definition": "likewise" },
    { "Headword": "iter itineris n.", "Definition": "journey, route" },
    { "Headword": "iterum", "Definition": "again" },
    { "Headword": "iubeō iubēre iussī iussum", "Definition": "bid, order" },
    { "Headword": "iūdex iūdicis m.", "Definition": "judge, juror" },
    { "Headword": "iūdicium -ī n.", "Definition": "judgment, decision, trial" },
    { "Headword": "iūdicō -āre", "Definition": "judge, decide" },
    { "Headword": "iugum -ī n.", "Definition": "yoke; ridge, chain of hills" },
    { "Headword": "iungō iungere iūnxī iūnctum", "Definition": "join" },
    { "Headword": "iūrō -āre", "Definition": "take an oath, swear; iūs iūrandum, oath" },
    { "Headword": "iūs iūris n.", "Definition": "right, justice, law" },
    { "Headword": "iūstus -a -um", "Definition": "right, just, fair" },
    { "Headword": "iuvenis -is m.", "Definition": "youth" },
    { "Headword": "iuvō iuvāre iūvī iūtum", "Definition": "help, assist; please, delight" },
    { "Headword": "labor -ōris m.", "Definition": "toil, exertion" },
    { "Headword": "labōrō -āre", "Definition": "toil, work; be in trouble or distress" },
    { "Headword": "lacrima -ae f.", "Definition": "tear" },
    { "Headword": "laedō laedere laesī laesum", "Definition": "injure by striking, hurt" },
    { "Headword": "laetus -a -um", "Definition": "glad, joyful" },
    { "Headword": "lapis lapidis m.", "Definition": "stone" },
    { "Headword": "lateō latēre latuī", "Definition": "lie hidden, be hidden" },
    { "Headword": "latus -eris n.", "Definition": "side, flank" },
    { "Headword": "lātus -a -um", "Definition": "broad, wide" },
    { "Headword": "laudō -āre", "Definition": "praise" },
    { "Headword": "laus laudis f.", "Definition": "praise, glory" },
    { "Headword": "lēgātus -ī m.", "Definition": "lieutenant, envoy" },
    { "Headword": "legiō -ōnis f.", "Definition": "legion" },
    { "Headword": "legō legere lēgī lēctum", "Definition": "gather, choose, read" },
    { "Headword": "levis -e", "Definition": "light, trivial" },
    { "Headword": "lēx lēgis f.", "Definition": "law" },
    { "Headword": "liber librī m.", "Definition": "book" },
    { "Headword": "līber lībera līberum", "Definition": "free; līberī (m. pl.): freeborn children" },
    { "Headword": "lībertās -ātis f.", "Definition": "freedom" },
    { "Headword": "libet libēre libuit or libitum est", "Definition": "it is pleasing (+ dat. + infin.)" },
    { "Headword": "libīdō -inis f.", "Definition": "passion, lust" },
    { "Headword": "licet licēre licuit licitum est", "Definition": "it is permitted (+ dat. + infin.)" },
    { "Headword": "licet", "Definition": "even though" },
    { "Headword": "līmen līminis n.", "Definition": "threshold" },
    { "Headword": "lingua -ae f.", "Definition": "tongue; language" },
    { "Headword": "littera -ae f.", "Definition": "letter, (pl.) literature" },
    { "Headword": "lītus -oris n.", "Definition": "shore" },
    { "Headword": "locus -ī m.", "Definition": "place; loca (n. pl.) region" },
    { "Headword": "longē", "Definition": "far, far off" },
    { "Headword": "longus -a -um", "Definition": "long, far" },
    { "Headword": "loquor loquī locūtus sum", "Definition": "speak, talk" },
    { "Headword": "lūmen luminis n.", "Definition": "light" },
    { "Headword": "lūna -ae f.", "Definition": "moon" },
    { "Headword": "lūx lūcis f.", "Definition": "light of day" },
    { "Headword": "maestus -a -um", "Definition": "sad, sorrowful; depressing" },
    { "Headword": "magis", "Definition": "more" },
    { "Headword": "magister magistrī m.", "Definition": "master, chief" },
    { "Headword": "māgnitūdō -inis f.", "Definition": "greatness, size" },
    { "Headword": "māgnus -a -um", "Definition": "great" },
    { "Headword": "māiōrēs māiōrum m.", "Definition": "ancestors" },
    { "Headword": "male", "Definition": "(adv.) badly" },
    { "Headword": "mālō mālle māluī", "Definition": "prefer" },
    { "Headword": "malus -a -um", "Definition": "bad, evil" },
    { "Headword": "maneō manēre mānsī mānsum", "Definition": "remain" },
    { "Headword": "manus -ūs f.", "Definition": "hand; band of men" },
    { "Headword": "mare -is n.", "Definition": "sea" },
    { "Headword": "marītus -ī m.", "Definition": "husband" },
    { "Headword": "māter mātris f.", "Definition": "mother" },
    { "Headword": "māteria -ae f.", "Definition": "material, subject matter; timber, lumber" },
    { "Headword": "medius -a -um", "Definition": "middle, central" },
    { "Headword": "membrum -ī n.", "Definition": "limb, member of the body" },
    { "Headword": "meminī meminisse", "Definition": "remember, recollect" },
    { "Headword": "memoria -ae f.", "Definition": "recollection, memory" },
    { "Headword": "mēns mentis f.", "Definition": "mind" },
    { "Headword": "mēnsa -ae f.", "Definition": "table" },
    { "Headword": "mereō merēre meruī meritum", "Definition": "deserve, merit; serve as a soldier" },
    { "Headword": "metuō metuere metuī", "Definition": "to fear, to dread" },
    { "Headword": "metus -ūs m.", "Definition": "fear, dread" },
    { "Headword": "meus -a -um", "Definition": "my" },
    { "Headword": "mīles -itis m.", "Definition": "soldier" },
    { "Headword": "mīlle (pl.) mīlia", "Definition": "thousand" },
    { "Headword": "mīror mīrārī mīrātus sum", "Definition": "wonder at, marvel at (+ acc.)" },
    { "Headword": "misceō miscēre miscuī mixtum", "Definition": "mix" },
    { "Headword": "miser misera miserum", "Definition": "wretched, pitiable" },
    { "Headword": "mittō mittere mīsī missum", "Definition": "send, let go" },
    { "Headword": "modo", "Definition": "just, just now; modo ... modo: now ... now, at one moment ... at another, sometimes ... sometimes" },
    { "Headword": "modus -ī m.", "Definition": "measure, manner, kind" },
    { "Headword": "moenia -ium n. pl.", "Definition": "walls, fortifications" },
    { "Headword": "mollis -e", "Definition": "soft, yielding, gentle" },
    { "Headword": "moneō monēre monuī monitum", "Definition": "warn, advise" },
    { "Headword": "mōns montis m.", "Definition": "mountain" },
    { "Headword": "mora -ae f.", "Definition": "delay, hindrance" },
    { "Headword": "morbus -ī m.", "Definition": "sickness, disease" },
    { "Headword": "morior morī mortuus sum", "Definition": "die" },
    { "Headword": "moror morārī morātus sum", "Definition": "delay" },
    { "Headword": "mors mortis f.", "Definition": "death" },
    { "Headword": "mortālis -e", "Definition": "liable to death, mortal; (as subst.) a mortal" },
    { "Headword": "mōs mōris m.", "Definition": "custom, habit; (pl.) character" },
    { "Headword": "moveō -ēre mōvī mōtum", "Definition": "move" },
    { "Headword": "mox", "Definition": "soon" },
    { "Headword": "mulier -eris f.", "Definition": "woman" },
    { "Headword": "multitūdō -inis f.", "Definition": "multitude, number" },
    { "Headword": "multus -a -um", "Definition": "much, many; multō, by far" },
    { "Headword": "mundus -ī m.", "Definition": "world, universe, heavens" },
    { "Headword": "mundus -a -um", "Definition": "clean, neat, elegant" },
    { "Headword": "mūnus mūneris n.", "Definition": "gift, offering; duty, obligation; (pl.) gladiatorial show" },
    { "Headword": "mūrus -ī m.", "Definition": "wall" },
    { "Headword": "mūtō -āre", "Definition": "change" },
    { "Headword": "nam or namque", "Definition": "for, indeed, really" },
    { "Headword": "narrō -āre", "Definition": "relate, recount" },
    { "Headword": "nāscor nāscī nātus sum", "Definition": "be born" },
    { "Headword": "nātūra -ae f.", "Definition": "nature" },
    { "Headword": "nātus -ī m.", "Definition": "son" },
    { "Headword": "nāvis -is f.", "Definition": "ship" },
    { "Headword": "ne (enclitic)", "Definition": "interrogative particle attached to the emphatic word in a question" },
    { "Headword": "nē", "Definition": "lest, that not" },
    { "Headword": "nec", "Definition": "and not, nor; nec ... nec, neither ... nor; → neque" },
    { "Headword": "necesse (indecl. adj.)", "Definition": "necessary" },
    { "Headword": "necessitās -tātis f.", "Definition": "necessity, need" },
    { "Headword": "nefās n. indecl.", "Definition": "impiety, wickedness" },
    { "Headword": "negō -āre", "Definition": "deny, refuse" },
    { "Headword": "negōtium -ī n.", "Definition": "business" },
    { "Headword": "nēmō", "Definition": "no one (gen. nūllīus, dat. nūllī, abl. nūllō or nūllā → nūllus -a -um)" },
    { "Headword": "nemus nemoris n.", "Definition": "grove, forest" },
    { "Headword": "neque", "Definition": "and not, nor; neque ... neque, neither ... nor; → nec" },
    { "Headword": "nesciō -scīre", "Definition": "not know, be ignorant" },
    { "Headword": "nisi, nī", "Definition": "if not, unless" },
    { "Headword": "niger nigra nigrum", "Definition": "black" },
    { "Headword": "nihil, nīl", "Definition": "nothing; not at all" },
    { "Headword": "nimis or nimium", "Definition": "excessively" },
    { "Headword": "nimius -a -um", "Definition": "too much, excessive" },
    { "Headword": "nōbilis -e", "Definition": "distinguished, noble; (as subst.) a nobleman or woman" },
    { "Headword": "noceō nocēre nocuī", "Definition": "harm" },
    { "Headword": "nōlō nōlle nōluī", "Definition": "be unwilling" },
    { "Headword": "nōmen -inis n.", "Definition": "name" },
    { "Headword": "nōn", "Definition": "not" },
    { "Headword": "nōndum", "Definition": "not yet" },
    { "Headword": "nōs nostrum/nostrī nōbīs nōs", "Definition": "we" },
    { "Headword": "nōscō nōscere nōvī nōtum", "Definition": "learn, know" },
    { "Headword": "noster nostra nostrum", "Definition": "our" },
    { "Headword": "nōtus -a -um", "Definition": "well-known" },
    { "Headword": "novus -a -um", "Definition": "new" },
    { "Headword": "nox noctis f.", "Definition": "night" },
    { "Headword": "nūdus -a -um", "Definition": "naked, bare" },
    { "Headword": "nūllus -a -um", "Definition": "not any, no one" },
    { "Headword": "num", "Definition": "interrogative particle implying negative answer" },
    { "Headword": "nūmen -inis n.", "Definition": "divine will, deity" },
    { "Headword": "numerus -ī m.", "Definition": "number, amount" },
    { "Headword": "numquam", "Definition": "never" },
    { "Headword": "nunc", "Definition": "now" },
    { "Headword": "nūntius -ī m.", "Definition": "messenger; news" },
    { "Headword": "ob", "Definition": "against, on account of (+acc)" },
    { "Headword": "occīdō -cīdere -cīdī -cīsum", "Definition": "kill, cut down" },
    { "Headword": "occupō -āre", "Definition": "seize, occupy; anticipate, do a thing first (+ infin.)" },
    { "Headword": "occurrō -currere -cucurrī -cursum", "Definition": "run to meet; come into one’s mind" },
    { "Headword": "oculus -ī m.", "Definition": "eye" },
    { "Headword": "ōdī ōdisse", "Definition": "hate" },
    { "Headword": "odium -ī n.", "Definition": "hatred" },
    { "Headword": "offerō offerre obtulī oblātum", "Definition": "present, offer, expose" },
    { "Headword": "officium -ī n.", "Definition": "service, duty" },
    { "Headword": "ōlim", "Definition": "formerly, at that time" },
    { "Headword": "omnis -e", "Definition": "all, every, as a whole" },
    { "Headword": "onus oneris n.", "Definition": "load, burden" },
    { "Headword": "opera -ae f.", "Definition": "labor, activity, work" },
    { "Headword": "oportet -ēre -uit", "Definition": "it is proper, right (+ acc. + infin.)" },
    { "Headword": "oppidum -ī n.", "Definition": "town" },
    { "Headword": "ops opis f.", "Definition": "assistance, resources" },
    { "Headword": "optō -āre", "Definition": "choose, select" },
    { "Headword": "opus operis n.", "Definition": "work" },
    { "Headword": "ōrātiō -ōnis f.", "Definition": "speech, address" },
    { "Headword": "orbis -is m.", "Definition": "circle; orbis terrārum: world" },
    { "Headword": "ōrdō -īnis m.", "Definition": "order, rank" },
    { "Headword": "orior orīrī ortus sum", "Definition": "arise, begin" },
    { "Headword": "ōrō -āre", "Definition": "pray" },
    { "Headword": "ōs ōris n.", "Definition": "mouth, face" },
    { "Headword": "os ossis n.", "Definition": "bone" },
    { "Headword": "ostendō ostendere ostendī ostentum", "Definition": "show, hold out" },
    { "Headword": "ōtium -ī n.", "Definition": "leisure" },
    { "Headword": "paene", "Definition": "almost" },
    { "Headword": "pār paris", "Definition": "equal" },
    { "Headword": "parcō parcere pepercī parsum", "Definition": "spare, be sparing of (+ dat.)" },
    { "Headword": "parēns -ntis m./f.", "Definition": "parent" },
    { "Headword": "pāreō pārēre pāruī", "Definition": "obey" },
    { "Headword": "pariō parere peperī partum", "Definition": "bring forth, give birth to; accomplish" },
    { "Headword": "parō -āre", "Definition": "prepare, acquire; parātus -a -um, ready" },
    { "Headword": "pars partis f.", "Definition": "part" },
    { "Headword": "parum", "Definition": "too little" },
    { "Headword": "parvus -a -um", "Definition": "small" },
    { "Headword": "pateō patēre patuī", "Definition": "lie open, extend; be evident or obvious" },
    { "Headword": "pater patris m.", "Definition": "father, ancestor" },
    { "Headword": "patior patī passus sum", "Definition": "permit, endure" },
    { "Headword": "patria -ae f.", "Definition": "fatherland, country" },
    { "Headword": "paucī -ae -a", "Definition": "few, a few" },
    { "Headword": "paulō, paulum", "Definition": "to only a small extent, slightly, a little" },
    { "Headword": "pauper -eris", "Definition": "poor, lowly" },
    { "Headword": "pāx pācis f.", "Definition": "peace" },
    { "Headword": "peccō -āre", "Definition": "commit a wrong, injure" },
    { "Headword": "pectus -oris n.", "Definition": "chest, breast" },
    { "Headword": "pecūnia -ae f.", "Definition": "money" },
    { "Headword": "pecus -oris n.", "Definition": "cattle, sheep" },
    { "Headword": "pellō pellere pepulī pulsum", "Definition": "strike, beat, push, drive" },
    { "Headword": "pendō pendere pependī pēnsum", "Definition": "weigh, hang, suspend; pay" },
    { "Headword": "per", "Definition": "through (+acc.)" },
    { "Headword": "perdō -dere -didī -ditum", "Definition": "destroy" },
    { "Headword": "pereō -īre -iī -itum", "Definition": "perish, be lost" },
    { "Headword": "pergō pergere perrēxī perrēctum", "Definition": "continue, proceed; awaken" },
    { "Headword": "perīculum -ī n.", "Definition": "danger" },
    { "Headword": "permittō -mittere -mīsī -missum", "Definition": "yield, allow, permit" },
    { "Headword": "perpetuus -a -um", "Definition": "unbroken, perpetual" },
    { "Headword": "pertineō -tinēre -tinuī", "Definition": "extend over, reach; refer to, pertain to, be the business of" },
    { "Headword": "perveniō -venīre -vēnī -ventum", "Definition": "arrive, reach" },
    { "Headword": "pēs pedis m.", "Definition": "foot" },
    { "Headword": "petō petere petīvī petītum", "Definition": "seek, aim at" },
    { "Headword": "pietās -tātis f.", "Definition": "sense of duty, devotion, esp. between parents and children" },
    { "Headword": "pius -a -um", "Definition": "dutiful, devoted, just, pious" },
    { "Headword": "placeō placēre placuī placitum", "Definition": "please" },
    { "Headword": "plēbs plēbis f.", "Definition": "the common people" },
    { "Headword": "plēnus -a -um", "Definition": "full" },
    { "Headword": "plērumque", "Definition": "generally" },
    { "Headword": "plērus- plēra- plērumque", "Definition": "the greater part, very many, most, the majority" },
    { "Headword": "poena -ae f.", "Definition": "penalty, punishment" },
    { "Headword": "poēta -ae m.", "Definition": "poet" },
    { "Headword": "pondus ponderis n.", "Definition": "weight" },
    { "Headword": "pōnō pōnere posuī positum", "Definition": "put, place; put aside" },
    { "Headword": "pontus -ī m.", "Definition": "the open sea, the deep" },
    { "Headword": "populus -ī m.", "Definition": "people" },
    { "Headword": "porta -ae f.", "Definition": "gate" },
    { "Headword": "portō -āre", "Definition": "carry a load" },
    { "Headword": "pōscō pōscere popōscī", "Definition": "demand, claim; inquire into" },
    { "Headword": "possum posse potuī", "Definition": "be able" },
    { "Headword": "post", "Definition": "after (adv. and prep. +acc.)" },
    { "Headword": "posteā", "Definition": "afterwards" },
    { "Headword": "posterus -a -um", "Definition": "next, later" },
    { "Headword": "postquam", "Definition": "after" },
    { "Headword": "potēns potentis", "Definition": "able, powerful" },
    { "Headword": "potestās -ātis f.", "Definition": "power" },
    { "Headword": "potis -e", "Definition": "powerful, able" },
    { "Headword": "praebeō -ēre -uī -itum", "Definition": "furnish, supply, render" },
    { "Headword": "praeceptum -ī n.", "Definition": "rule, precept; command" },
    { "Headword": "praecipiō -cipere -cēpī -ceptum", "Definition": "anticipate, advise, warn" },
    { "Headword": "praeda -ae f.", "Definition": "booty, prey" },
    { "Headword": "praemium -ī n.", "Definition": "bounty, reward" },
    { "Headword": "praesēns -ntis", "Definition": "present, in person, ready" },
    { "Headword": "praesidium -ī n.", "Definition": "garrison, protection" },
    { "Headword": "praestō -stāre -stitī -stitum", "Definition": "excel, exhibit" },
    { "Headword": "praeter", "Definition": "by, along, past; besides, except (+ acc.)" },
    { "Headword": "praetereā", "Definition": "besides, moreover" },
    { "Headword": "praetor -ōris m.", "Definition": "praetor, one of the chief Roman magistrates" },
    { "Headword": "precor -ārī", "Definition": "pray, invoke" },
    { "Headword": "premō premere pressī pressum", "Definition": "press, pursue, overwhelm" },
    { "Headword": "pretium -ī n.", "Definition": "price, worth, reward; pretium operae: a reward for trouble" },
    { "Headword": "prex precis f.", "Definition": "prayers, entreaties" },
    { "Headword": "prīmum", "Definition": "at first, firstly" },
    { "Headword": "prīmus -a -um", "Definition": "first" },
    { "Headword": "prīnceps -cipis", "Definition": "first, chief; (as subst.) leader, person in charge" },
    { "Headword": "prīncipium -ī n.", "Definition": "beginning" },
    { "Headword": "prior prius", "Definition": "earlier, preceding" },
    { "Headword": "prīvātus -a -um", "Definition": "personal, private" },
    { "Headword": "prius or priusquam", "Definition": "before" },
    { "Headword": "prō", "Definition": "for, on behalf of, in proportion to (+abl.)" },
    { "Headword": "probō -āre", "Definition": "approve, prove; convince one (dat.) of a thing (acc.)" },
    { "Headword": "prōcēdō -cēdere -cessī -cessum", "Definition": "go forth, advance" },
    { "Headword": "procul", "Definition": "at a distance" },
    { "Headword": "prōdō prōdere prōdidī prōditum", "Definition": "publish, hand down; give over, betray" },
    { "Headword": "proelium -ī n.", "Definition": "battle" },
    { "Headword": "proficīscor -ficīscī -fectus sum", "Definition": "set forth, go" },
    { "Headword": "prohibeō -ēre -uī -itum", "Definition": "restrain, keep away" },
    { "Headword": "prōmittō -mittere -mīsī -missum", "Definition": "send forth, offer" },
    { "Headword": "prope", "Definition": "near, next; (comp.) propior, (superl.) proximus; (adv.) prope, nearly, almost" },
    { "Headword": "properō -āre", "Definition": "hasten, speed" },
    { "Headword": "prōpōnō -pōnere -posuī -positum", "Definition": "put forth, propose, present" },
    { "Headword": "proprius -a -um", "Definition": "one’s own, peculiar" },
    { "Headword": "propter", "Definition": "because of (+ acc.)" },
    { "Headword": "prōsum prodesse profuī", "Definition": "be of use, do good, help (+ dat.)" },
    { "Headword": "prōtinus", "Definition": "at once, forthwith" },
    { "Headword": "prōvincia -ae f.", "Definition": "province; official duty" },
    { "Headword": "pūblicus -a -um", "Definition": "public, belonging to the state" },
    { "Headword": "pudor pudōris m.", "Definition": "sense of shame, modesty, propriety" },
    { "Headword": "puella -ae f.", "Definition": "girl; girl-friend" },
    { "Headword": "puer puerī m.", "Definition": "boy; slave" },
    { "Headword": "pūgna -ae f.", "Definition": "fist-fight; battle" },
    { "Headword": "pugnō -āre", "Definition": "fight" },
    { "Headword": "pulcher -chra -chrum", "Definition": "beautiful" },
    { "Headword": "putō -āre", "Definition": "think, suppose" },
    { "Headword": "quā", "Definition": "where, how" },
    { "Headword": "quaerō -rere -sīvī -sītum", "Definition": "seek, inquire" },
    { "Headword": "quālis -e", "Definition": "of what kind? what?" },
    { "Headword": "quam", "Definition": "how?; (after comparative) than" },
    { "Headword": "quamquam", "Definition": "however, although" },
    { "Headword": "quamvīs", "Definition": "however you like; although" },
    { "Headword": "quandō", "Definition": "when?; since; sī quandō: if ever" },
    { "Headword": "quantum", "Definition": "(adv.) how much? how greatly? how much! how greatly! as much as" },
    { "Headword": "quantus -a -um", "Definition": "(interr.) how great? (rel.) of what size, amount, etc. (as subst.) what amount? (rel.) which amount; quantī, at what price? (rel.) at which price" },
    { "Headword": "quārē", "Definition": "how? why?" },
    { "Headword": "quasi", "Definition": "as if" },
    { "Headword": "quattuor", "Definition": "four" },
    { "Headword": "que", "Definition": "and (postpositive enclitic)" },
    { "Headword": "quemadmodum", "Definition": "in what manner, how" },
    { "Headword": "queror querī questus sum", "Definition": "complain of, lament" },
    { "Headword": "quī quae quod", "Definition": "who, which, what" },
    { "Headword": "quia", "Definition": "because" },
    { "Headword": "quīcumque quaecumque quodcumque", "Definition": "who-, whatever" },
    { "Headword": "quīdam quaedam quoddam", "Definition": "a certain one, someone" },
    { "Headword": "quidem", "Definition": "certainly, at least" },
    { "Headword": "quiēscō quiēscere quiēvī quiētum", "Definition": "keep quiet; sleep" },
    { "Headword": "quīn", "Definition": "(adv.) indeed, in fact; (conjunction) so that ... not (+ subj.)" },
    { "Headword": "quīppe", "Definition": "(adv.) indeed, surely" },
    { "Headword": "quis quid", "Definition": "who? what? which?" },
    { "Headword": "quisquam quicquam/quidquam", "Definition": "any (single) person, anyone at all" },
    { "Headword": "quisque quaeque quidque", "Definition": "each one, everyone" },
    { "Headword": "quisquis quidquid", "Definition": "whoever, whichever" },
    { "Headword": "quō", "Definition": "for which reason; to or in what place; to what end, for what purpose?" },
    { "Headword": "quōmodo", "Definition": "in what way, how?" },
    { "Headword": "quondam", "Definition": "formerly, once" },
    { "Headword": "quoniam", "Definition": "since, seeing that" },
    { "Headword": "quoque", "Definition": "also, too" },
    { "Headword": "quotiēns", "Definition": "interr. how many times? how often? rel. as often as, whenever" },
    { "Headword": "rapiō rapere rapuī raptum", "Definition": "seize, tear away" },
    { "Headword": "rārus -a -um", "Definition": "wide apart, loose, thin; rare, seldom" },
    { "Headword": "ratiō -ōnis f.", "Definition": "method, plan, reason" },
    { "Headword": "recēdō -cēdere -cessī -cessum", "Definition": "step back, recoil, recede, withdraw" },
    { "Headword": "recēns -ntis", "Definition": "fresh, new" },
    { "Headword": "recipiō -cipere -cēpī -ceptum", "Definition": "take back, receive; sē recipere, betake oneself, go" },
    { "Headword": "rēctus -a -um", "Definition": "straight, direct" },
    { "Headword": "reddō -dere -didī -ditum", "Definition": "return, give back" },
    { "Headword": "redeō -īre -iī -itum", "Definition": "go back, return" },
    { "Headword": "referō referre rettulī relātum", "Definition": "bring back; report" },
    { "Headword": "regiō -ōnis f.", "Definition": "boundary, region" },
    { "Headword": "rēgius -a -um", "Definition": "kingly, royal" },
    { "Headword": "rēgnum -ī n.", "Definition": "kingship, kingdom" },
    { "Headword": "regō regere rēxī rēctum", "Definition": "guide, rule" },
    { "Headword": "relinquō -linquere -līquī -lictum", "Definition": "abandon" },
    { "Headword": "reliquus -a -um", "Definition": "remaining, rest" },
    { "Headword": "reor rērī rātus sum", "Definition": "think, imagine, suppose, deem" },
    { "Headword": "reperiō -perīre -pperī -pertum", "Definition": "find, find out" },
    { "Headword": "repetō -petere -petīvī -petītum", "Definition": "demand, exact; revisit; call to mind, recollect; repeat" },
    { "Headword": "rēs reī f.", "Definition": "thing (rēs pūblica, commonwealth; rēs familiāris, family property, estate; rēs mīlitāris, art of war; rēs novae, revolution)" },
    { "Headword": "respicio -ere -spēxī -spectum", "Definition": "look back, regard, consider" },
    { "Headword": "respondeō -spondēre -spondī -spōnsum", "Definition": "answer" },
    { "Headword": "retineō -tinēre -tinuī -tentum", "Definition": "hold back, keep" },
    { "Headword": "revertō -vertere -vertī", "Definition": "turn back" },
    { "Headword": "revocō -āre", "Definition": "call back, recall" },
    { "Headword": "reus -ī m.", "Definition": "defendant" },
    { "Headword": "rēx rēgis m.", "Definition": "king" },
    { "Headword": "rīdeō -ēre rīsī rīsum", "Definition": "laugh, laugh at" },
    { "Headword": "rīpa -ae f.", "Definition": "bank of a river" },
    { "Headword": "rogō -āre", "Definition": "ask" },
    { "Headword": "rumpō rumpere rūpī ruptum", "Definition": "break, rupture" },
    { "Headword": "rūrsus", "Definition": "back, again" },
    { "Headword": "rūs rūris n.", "Definition": "country" },
    { "Headword": "sacer sacra sacrum", "Definition": "holy, sacred" },
    { "Headword": "sacerdōs -dōtis m./f.", "Definition": "priest, priestess" },
    { "Headword": "saeculum -ī n.", "Definition": "generation, age, century" },
    { "Headword": "saepe", "Definition": "often" },
    { "Headword": "saevus -a -um", "Definition": "fierce, raging, wrathful" },
    { "Headword": "salūs -ūtis f.", "Definition": "health, safety" },
    { "Headword": "sānctus -a -um", "Definition": "sacred, inviolable" },
    { "Headword": "sanguis -inis m.", "Definition": "blood" },
    { "Headword": "sānus -a -um", "Definition": "sound, sane" },
    { "Headword": "sapiēns -ntis", "Definition": "wise; (as subst.) wise man, sage, philosopher" },
    { "Headword": "sapientia -ae f.", "Definition": "wisdom" },
    { "Headword": "satis, sat", "Definition": "enough, sufficient, sufficiently" },
    { "Headword": "saxum -ī n.", "Definition": "rock, cliff, crag" },
    { "Headword": "scelus -eris n.", "Definition": "crime, sin" },
    { "Headword": "scientia -ae f.", "Definition": "knowledge" },
    { "Headword": "scīlicet", "Definition": "certainly, of course" },
    { "Headword": "sciō -īre -īvī/-iī -ītum", "Definition": "know" },
    { "Headword": "scrībō scrībere scrīpsī scrīptum", "Definition": "write" },
    { "Headword": "secundus -a -um", "Definition": "following; favorable; (as numeral) second" },
    { "Headword": "sēcūrus -a -um", "Definition": "free from care, tranquil; careless" },
    { "Headword": "sed", "Definition": "but" },
    { "Headword": "sedeō sedēre sēdī sessum", "Definition": "sit" },
    { "Headword": "sēdēs -is f.", "Definition": "seat, abode, habitation" },
    { "Headword": "semel", "Definition": "once" },
    { "Headword": "semper", "Definition": "always, ever" },
    { "Headword": "senātus -ūs m.", "Definition": "senate" },
    { "Headword": "senex -is m.", "Definition": "old man, elder; senior, older" },
    { "Headword": "sēnsus -ūs m.", "Definition": "feeling, emotion, sense" },
    { "Headword": "sententia -ae f.", "Definition": "opinion, judgment" },
    { "Headword": "sentiō sentīre sēnsī sēnsum", "Definition": "perceive, feel, hear, see" },
    { "Headword": "sepulcrum -ī n.", "Definition": "place of burial, tomb, grave" },
    { "Headword": "sequor sequī secūtus sum", "Definition": "follow" },
    { "Headword": "sermō -ōnis m.", "Definition": "conversation, discourse" },
    { "Headword": "serviō -īre", "Definition": "be a slave, serve (+ dat.)" },
    { "Headword": "servō -āre", "Definition": "save, watch over" },
    { "Headword": "servus -ī m.", "Definition": "slave" },
    { "Headword": "seu", "Definition": "whether; seu ... seu: whether ... or → sīve" },
    { "Headword": "sī", "Definition": "if" },
    { "Headword": "sīc", "Definition": "in this manner, thus; sīc ... ut: in the same way as" },
    { "Headword": "sīcut", "Definition": "just as" },
    { "Headword": "sīdus -eris n.", "Definition": "star, constellation" },
    { "Headword": "sīgnum -ī n.", "Definition": "sign, standard, mark" },
    { "Headword": "silva -ae f.", "Definition": "forest, grove" },
    { "Headword": "similis -e", "Definition": "like, similar" },
    { "Headword": "simul", "Definition": "at the same time" },
    { "Headword": "sine", "Definition": "without (+ abl.)" },
    { "Headword": "singulī -ae -a", "Definition": "one each" },
    { "Headword": "sinō sinere sīvī situm", "Definition": "allow, let go" },
    { "Headword": "sinus -ūs m.", "Definition": "fold of a garment; lap, bay, gulf" },
    { "Headword": "sīve", "Definition": "whether; sīve ... sīve: whether ... or → seu" },
    { "Headword": "socius -a -um", "Definition": "friendly, allied; socius -ī m.: partner, comrade" },
    { "Headword": "sōl sōlis m.", "Definition": "sun" },
    { "Headword": "soleō -ēre -uī -itum", "Definition": "be accustomed" },
    { "Headword": "sōlum", "Definition": "only, merely" },
    { "Headword": "solvō solvere solvī solūtum", "Definition": "release, set sail" },
    { "Headword": "sōlus -a -um", "Definition": "only, alone" },
    { "Headword": "somnus -ī m.", "Definition": "sleep, slumber; (pl.) dreams" },
    { "Headword": "sonō sonāre sonuī sonitum", "Definition": "sound, resound" },
    { "Headword": "soror -ōris f.", "Definition": "sister" },
    { "Headword": "sors sortis f.", "Definition": "lot, fate, destiny; oracle" },
    { "Headword": "spargō spargere sparsī sparsum", "Definition": "scatter" },
    { "Headword": "spatium -ī n.", "Definition": "space" },
    { "Headword": "speciēs -ēī f.", "Definition": "aspect, appearance" },
    { "Headword": "spectō -āre", "Definition": "look at, consider" },
    { "Headword": "spērō -āre", "Definition": "to hope" },
    { "Headword": "spēs speī f.", "Definition": "hope" },
    { "Headword": "spīritus -ūs m.", "Definition": "breath, life, spirit" },
    { "Headword": "statim", "Definition": "immediately" },
    { "Headword": "statuō -ere -uī -ūtum", "Definition": "set up, determine" },
    { "Headword": "stella -ae f.", "Definition": "star" },
    { "Headword": "stō stāre stetī statum", "Definition": "stand" },
    { "Headword": "studeō -ēre -uī", "Definition": "be eager, be zealous, care for (+ dat.)" },
    { "Headword": "studium -ī n.", "Definition": "eagerness, zeal" },
    { "Headword": "sub", "Definition": "under, close to (+acc. or abl.)" },
    { "Headword": "subeō -īre -iī -itum", "Definition": "go under; endure" },
    { "Headword": "subitō", "Definition": "suddenly, unexpectedly" },
    { "Headword": "sui sibi sē/sēsē", "Definition": "him- her- itself, themselves" },
    { "Headword": "sum esse fuī futūrum", "Definition": "be, exist; fut. infin. often = fore, impf. subj. often = forem for essem" },
    { "Headword": "sūmō sūmere sūmpsī sūmptum", "Definition": "take up" },
    { "Headword": "super", "Definition": "over (adv. and prep. +acc.)" },
    { "Headword": "superbus -a -um", "Definition": "overbearing, proud, haughty" },
    { "Headword": "superī -ōrum m. pl.", "Definition": "those above, i.e. the gods" },
    { "Headword": "superō -āre", "Definition": "overcome, surpass, defeat" },
    { "Headword": "supersum -esse -fuī", "Definition": "remain, survive; be superfluous (to)" },
    { "Headword": "superus -a -um", "Definition": "situated above, upper" },
    { "Headword": "supplicium -ī n.", "Definition": "punishment, penalty" },
    { "Headword": "suprā", "Definition": "above, beyond (adv. and prep. +acc.)" },
    { "Headword": "surgō surgere surrēxī surrēctum", "Definition": "rise" },
    { "Headword": "suscipiō -cipere -cēpī ceptum", "Definition": "take up" },
    { "Headword": "sustineō sustinēre sustinuī sustentum", "Definition": "hold up, sustain" },
    { "Headword": "suus -a -um", "Definition": "his own, her own, its own" },
    { "Headword": "taceō -ēre -uī -itum", "Definition": "be silent; tacitus -a -um, silent" },
    { "Headword": "tālis tāle", "Definition": "such" },
    { "Headword": "tam", "Definition": "so, so much" },
    { "Headword": "tamen", "Definition": "nevertheless, still" },
    { "Headword": "tamquam", "Definition": "so as, just as" },
    { "Headword": "tandem", "Definition": "finally" },
    { "Headword": "tangō tangere tetigī tāctum", "Definition": "touch" },
    { "Headword": "tantum, tantummodo", "Definition": "only" },
    { "Headword": "tantus -a -um", "Definition": "so great, so much; (as pronoun) such a quantity, so much; tantī, at such a price, of such worth" },
    { "Headword": "tardus -a -um", "Definition": "slow, sluggish, lingering" },
    { "Headword": "tēctum -ī n.", "Definition": "roof; building, house" },
    { "Headword": "tegō tegere tēxī tēctum", "Definition": "cover, conceal" },
    { "Headword": "tellus tellūris f.", "Definition": "earth" },
    { "Headword": "tēlum -ī n.", "Definition": "missile, weapon, spear" },
    { "Headword": "tempestas -tātis f.", "Definition": "period of time, season; bad weather, storm" },
    { "Headword": "templum -ī n.", "Definition": "consecrated ground; temple" },
    { "Headword": "tempus -oris n.", "Definition": "time" },
    { "Headword": "tendō tendere tetendī tentum", "Definition": "stretch, extend, direct (one’s steps or course)" },
    { "Headword": "tenebrae -brārum f. pl.", "Definition": "darkness, the shadows" },
    { "Headword": "teneō -ēre -uī tentum", "Definition": "hold, keep" },
    { "Headword": "tener -era -erum", "Definition": "tender" },
    { "Headword": "temptō -āre", "Definition": "try, test" },
    { "Headword": "tergum -ī n.", "Definition": "back, rear; ā tergō: from the rear" },
    { "Headword": "terra -ae f.", "Definition": "land" },
    { "Headword": "terreō terrēre terruī territum", "Definition": "terrify, frighten" },
    { "Headword": "tertius -a -um", "Definition": "third" },
    { "Headword": "testis -is m.", "Definition": "witness" },
    { "Headword": "timeō -ēre -uī", "Definition": "to fear, to dread" },
    { "Headword": "timor -ōris m.", "Definition": "fear" },
    { "Headword": "tollō tollere sustulī sublātum", "Definition": "raise up, destroy" },
    { "Headword": "tot", "Definition": "so many" },
    { "Headword": "tōtus -a -um", "Definition": "whole, entire" },
    { "Headword": "trādō -dere -didī -ditum", "Definition": "hand over, yield" },
    { "Headword": "trahō trahere trāxī trāctum", "Definition": "drag, draw" },
    { "Headword": "trānseō -īre -iī -itum", "Definition": "go across" },
    { "Headword": "trēs tria", "Definition": "three" },
    { "Headword": "tribūnus -ī m.", "Definition": "tribune, title of various Roman officials, as mīlitum, plēbis, aerāriī" },
    { "Headword": "trīstis -e", "Definition": "sad, solemn, grim" },
    { "Headword": "tū tuī tibi tē", "Definition": "you (sing.)" },
    { "Headword": "tum or tunc", "Definition": "then" },
    { "Headword": "turba -ae f.", "Definition": "crowd, uproar" },
    { "Headword": "turbō -āre", "Definition": "disturb, confuse" },
    { "Headword": "turpis -e", "Definition": "ugly, unsightly; disgraceful" },
    { "Headword": "tūtus -a -um", "Definition": "safe, protected" },
    { "Headword": "tuus -a -um", "Definition": "your" },
    { "Headword": "vacō vacāre", "Definition": "be empty, open, unoccupied" },
    { "Headword": "vacuus -a -um", "Definition": "empty" },
    { "Headword": "vagus -a -um", "Definition": "wandering, shifting" },
    { "Headword": "valeō valēre valuī", "Definition": "be strong, excel, be valid, prevail; valē: farewell!" },
    { "Headword": "validus -a -um", "Definition": "strong" },
    { "Headword": "vanus -a -um", "Definition": "empty; false, deceitful" },
    { "Headword": "varius -a -um", "Definition": "changing, varied, various" },
    { "Headword": "vātēs -is m.", "Definition": "poet, bard" },
    { "Headword": "ubi", "Definition": "where, when" },
    { "Headword": "ve", "Definition": "or (postpositive enclitic)" },
    { "Headword": "vehō vehere vēxī vectum", "Definition": "carry; vehor vehī vectus sum: travel, ride" },
    { "Headword": "vel", "Definition": "or else, or; even; vel ... vel: either … or" },
    { "Headword": "velut", "Definition": "even as, just as" },
    { "Headword": "veniō venīre vēnī ventum", "Definition": "come" },
    { "Headword": "ventus -ī m.", "Definition": "wind" },
    { "Headword": "verbum -ī n.", "Definition": "word" },
    { "Headword": "vērē", "Definition": "truly" },
    { "Headword": "vereor verērī veritus sum", "Definition": "fear, stand in awe of" },
    { "Headword": "vērō", "Definition": "in fact, certainly, without doubt" },
    { "Headword": "vertō vertere vertī versum", "Definition": "turn" },
    { "Headword": "vērus -a -um", "Definition": "true" },
    { "Headword": "vester vestra vestrum", "Definition": "your" },
    { "Headword": "vestīgium -ī n.", "Definition": "footstep, footprint, track" },
    { "Headword": "vestis -is f.", "Definition": "garment, robe, clothing" },
    { "Headword": "vetō -āre vetuī vetītum", "Definition": "forbid" },
    { "Headword": "vetus veteris", "Definition": "old" },
    { "Headword": "via -ae f.", "Definition": "way, street" },
    { "Headword": "vīcīnus -a -um", "Definition": "neighboring, near" },
    { "Headword": "victor -ōris m.", "Definition": "conqueror" },
    { "Headword": "victōria -ae f.", "Definition": "victory" },
    { "Headword": "videō vidēre vīdī vīsum", "Definition": "see" },
    { "Headword": "vincō vincere vīcī victum", "Definition": "conquer" },
    { "Headword": "vinculum -ī n.", "Definition": "bond, fetter, tie" },
    { "Headword": "vīnum -ī n.", "Definition": "vine, wine" },
    { "Headword": "vir virī m.", "Definition": "man" },
    { "Headword": "virgō -inis f.", "Definition": "maiden, virgin, girl" },
    { "Headword": "virtūs -ūtis f.", "Definition": "valor, manliness, virtue" },
    { "Headword": "vīs f.", "Definition": "force; (acc.) vim, (abl.) vī; (pl.) vīrēs, strength" },
    { "Headword": "vīta -ae f.", "Definition": "life" },
    { "Headword": "vitium -ī n.", "Definition": "flaw, fault, crime" },
    { "Headword": "vītō -āre", "Definition": "avoid, shun" },
    { "Headword": "vīvō vīvere vīxī vīctum", "Definition": "live" },
    { "Headword": "vix", "Definition": "scarcely" },
    { "Headword": "ūllus -a -um", "Definition": "any, anyone" },
    { "Headword": "ultimus -a -um", "Definition": "farthest, final, last, ultimate" },
    { "Headword": "ultrā", "Definition": "beyond, further (adv. and prep. + acc.)" },
    { "Headword": "umbra -ae f.", "Definition": "shade, shadow" },
    { "Headword": "umquam", "Definition": "ever" },
    { "Headword": "unda -ae f.", "Definition": "wave, flowing water, water" },
    { "Headword": "unde", "Definition": "from where" },
    { "Headword": "undique", "Definition": "from all sides, on all sides" },
    { "Headword": "ūnus -a -um", "Definition": "one" },
    { "Headword": "vocō -āre", "Definition": "call" },
    { "Headword": "volō velle voluī", "Definition": "wish, be willing" },
    { "Headword": "volucer -cris -cre", "Definition": "flying" },
    { "Headword": "volucris -is f./m.", "Definition": "bird" },
    { "Headword": "voluntās -ātis f.", "Definition": "wish, desire" },
    { "Headword": "voluptās -ātis f.", "Definition": "pleasure, enjoyment" },
    { "Headword": "vōs", "Definition": "you (pl.); (gen.) vestrum/vestrī, (dat./abl.) vōbīs, (acc.) vōs" },
    { "Headword": "vōtum -ī n.", "Definition": "solemn promise, vow; hope" },
    { "Headword": "vōx vōcis f.", "Definition": "voice, utterance" },
    { "Headword": "urbs urbis f.", "Definition": "city" },
    { "Headword": "ūsque", "Definition": "up to; continuously" },
    { "Headword": "ūsus -ūs m.", "Definition": "use, experience" },
    { "Headword": "ut, utī", "Definition": "as (+ indic.); so that, with the result that (+ subj.); (in questions) in what manner, how; (exclam.) to what an extent! how!" },
    { "Headword": "uterque utraque utrumque", "Definition": "each of two" },
    { "Headword": "ūtilis -e", "Definition": "useful" },
    { "Headword": "ūtor ūtī ūsus sum", "Definition": "use, consume, employ (+ abl.)" },
    { "Headword": "utrum", "Definition": "whether; utrum ... an: whether ... or" },
    { "Headword": "vulgō", "Definition": "commonly" },
    { "Headword": "vulgus -ī n. and m.", "Definition": "the common people" },
    { "Headword": "vulnus -eris n.", "Definition": "wound" },
    { "Headword": "vultus -ūs m.", "Definition": "look, expression, face" },
    { "Headword": "uxor uxōris f.", "Definition": "wife" },
];

// Shuffle function to randomize the vocabulary order
function shuffle(array) {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
}

// App state variables
let currentWordIndex = 0;
let score = 0;

// Initialize the app with shuffled vocabulary
const shuffledVocabulary = shuffle([...vocabulary]);

// Function to get the current question
function getCurrentQuestion() {
    return shuffledVocabulary[currentWordIndex];
}

// Function to check the answer
function checkAnswer(userAnswer) {
    const word = shuffledVocabulary[currentWordIndex];
    const correctAnswer = word.Definition.toLowerCase();

    if (userAnswer === correctAnswer) {
        score++;
        word.interval *= 2; // Double the interval
        return { correct: true, correctAnswer };
    } else {
        word.interval = 1; // Reset the interval
        return { correct: false, correctAnswer };
    }
}

// Function to update the progress
function updateProgress() {
    return (currentWordIndex / shuffledVocabulary.length) * 100;
}

// Function to move to the next question
function nextQuestion() {
    currentWordIndex++;
    return currentWordIndex < shuffledVocabulary.length;
}